---
- name: Crear estructura de directorios
  file:
    path: /tmp/2do_parcial/{{ item }}
    state: directory
    mode: '0755'
  with_items:
    - alumno
    - equipo

- name: Generar archivo datos_alumno.txt
  template:
    src: datos_alumno.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt
    mode: '0644'

- name: Generar archivo datos_equipo.txt
  template:
    src: datos_equipo.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt
    mode: '0644'

- name: Configurar sudoers para el grupo 2PSupervisores
  copy:
    dest: /etc/sudoers.d/2PSupervisores
    content: |
      %2PSupervisores ALL=(ALL) NOPASSWD: ALL
    mode: '0440'
  become: true  # Esto otorga privilegios de root a la tarea

- name: Mostrar mensaje de éxito
  debug:
    msg: "Archivo configurado exitosamente."
